name: ci

on:
  push:
    branches:
     - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 4 1,15 * *' # twice a month

jobs:
  industrial_ci:
    strategy:
      matrix:
        ros_distro: [ melodic, noetic ]
        ros_repo: [ main, testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: ${{ matrix.ros_repo }}

  downstream_ci:
    needs: [industrial_ci]
    strategy:
      matrix:
        ros_distro: [ melodic, noetic ]
        ros_repo: [ main, testing ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.ros_distro }}
          ROS_REPO: ${{ matrix.ros_repo }}
          DOWNSTREAM_WORKSPACE: .downstream_ci.rosinstall
